
#===============================================#
#                                               #
#      This file is auto-generated by tool      #
#              2021-11-12 02:42:11              #
#                                               #
#===============================================#

extends ConfigTable

class DataType:
	extends Reference
	var test: String

	func _init(field_value_map := {}):
		for key in field_value_map.keys():
			set(key, field_value_map[key])

func _get_data_table():
	# DataType.new({})
	return [
	]

func by(field_name, v) -> DataType:
	return ._by(field_name, v) as DataType

func _get_data_head_def():
	return [
		"test",
	]

# func by_field1(v) -> DataType:
#   return by("field1", v)
func by_test(v) -> DataType:
	return by("test", v)



func all_by_test(v) -> Array:
	return _all_by("test", v)



func has_test(v) -> bool:
	return has("test", v)

