#====================================#
#                                    #
# The file is auto-generated by tool #
#         2023-4-1 16:55:12         #
#                                    #
#====================================#

extends ConfigHelperBase

var item := preload("configs/item.gd").new()
var test := preload("configs/test.gd").new()











