#====================================#
#                                    #
# The file is auto-generated by tool #
#        2021-11-11 15:18:53        #
#                                    #
#====================================#

extends ConfigHelperBase

var people := preload("configs/people.gd").new()
var people_sub := preload("configs/people_sub.gd").new()











